<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ApplicationIcon>Assets/icon.ico</ApplicationIcon>
    <AssemblyName>BusinessSuite</AssemblyName>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

    <CFBundleDisplayName>BusinessSuite</CFBundleDisplayName>
    <CFBundleIdentifier>com.alanwar.businesssuite</CFBundleIdentifier>
    <CFBundlePackageType>APPL</CFBundlePackageType>
    <CFBundleShortVersionString>1.0.0</CFBundleShortVersionString>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.10" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.10" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.10" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.8" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.10" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.10" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.10">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" Version="2.0.0-rc6.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="ReactiveUI" Version="22.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessSuite.DAL\BusinessSuite.DAL.csproj" />
    <ProjectReference Include="..\BusinessSuite.BLL\BusinessSuite.BLL.csproj" />
  </ItemGroup>

  <PropertyGroup>
  <AvaloniaXamlDiagnostics>true</AvaloniaXamlDiagnostics>
</PropertyGroup>
</Project>
