// <auto-generated />
using System;
using BusinessSuite.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessSuite.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260205125019_AddStockManagementAndAttachments")]
    partial class AddStockManagementAndAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("BusinessSuite.DAL.Entities.Business", b =>
                {
                    b.Property<int>("BusinessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GSTIN")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GstType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IFSC")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGSTRegistered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.HasKey("BusinessID");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GSTIN")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("GstTreatment")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("IFSC")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerID");

                    b.HasIndex("BusinessId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.GstRate", b =>
                {
                    b.Property<int>("RateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("TEXT");

                    b.HasKey("RateID");

                    b.ToTable("GstRates");

                    b.HasData(
                        new
                        {
                            RateID = 1,
                            Description = "Exempt/Nil Rated",
                            Percentage = 0m
                        },
                        new
                        {
                            RateID = 2,
                            Description = "Essential Items",
                            Percentage = 5m
                        },
                        new
                        {
                            RateID = 3,
                            Description = "Standard Rate (Lower)",
                            Percentage = 12m
                        },
                        new
                        {
                            RateID = 4,
                            Description = "Standard Rate",
                            Percentage = 18m
                        },
                        new
                        {
                            RateID = 5,
                            Description = "Luxury/Demerit Items",
                            Percentage = 28m
                        });
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoRoundOff")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsItemLevelDiscount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfSupply")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReverseCharge")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RoundOff")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ShippingCharges")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TermsAndConditions")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalCGST")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalIGST")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalSGST")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("InvoiceID");

                    b.HasIndex("BusinessID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("InvoiceItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CGST_Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("CGST_Rate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HSNCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IGST_Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("IGST_Rate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SGST_Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SGST_Rate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("InvoiceItemID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("ProductID");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.LicenseActivation", b =>
                {
                    b.Property<int>("LicenseActivationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActivatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BusinessID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiresOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("HardwareIdHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseKeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LicenseActivationID");

                    b.ToTable("LicenseActivations");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HSNCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQty")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.HasIndex("BusinessID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsAutoRoundOff")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsItemLevelDiscount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PODate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfSupply")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReverseCharge")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RoundOff")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ShippingCharges")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TermsAndConditions")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalCGST")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalIGST")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalSGST")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("VendorBillPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("VendorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PurchaseOrderID");

                    b.HasIndex("BusinessId");

                    b.HasIndex("VendorId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<int>("PurchaseOrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CGST_Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("CGST_Rate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HSNCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IGST_Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("IGST_Rate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PurchaseOrderID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SGST_Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SGST_Rate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PurchaseOrderItemID");

                    b.HasIndex("ProductID");

                    b.HasIndex("PurchaseOrderID");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.Settings", b =>
                {
                    b.Property<int>("SettingsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoBackup")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SettingsID");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.StockTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReferenceID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionID");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ProductID");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.UnitOfMeasure", b =>
                {
                    b.Property<int>("UnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UnitID");

                    b.ToTable("UnitsOfMeasure");

                    b.HasData(
                        new
                        {
                            UnitID = 1,
                            BusinessId = 0,
                            Description = "Pieces",
                            Name = "PCS"
                        },
                        new
                        {
                            UnitID = 2,
                            BusinessId = 0,
                            Description = "Box",
                            Name = "BOX"
                        },
                        new
                        {
                            UnitID = 3,
                            BusinessId = 0,
                            Description = "Kilograms",
                            Name = "KG"
                        },
                        new
                        {
                            UnitID = 4,
                            BusinessId = 0,
                            Description = "Meters",
                            Name = "MTR"
                        },
                        new
                        {
                            UnitID = 5,
                            BusinessId = 0,
                            Description = "Numbers",
                            Name = "NOS"
                        },
                        new
                        {
                            UnitID = 6,
                            BusinessId = 0,
                            Description = "Litres",
                            Name = "LTR"
                        },
                        new
                        {
                            UnitID = 7,
                            BusinessId = 0,
                            Description = "Grams",
                            Name = "GMS"
                        },
                        new
                        {
                            UnitID = 8,
                            BusinessId = 0,
                            Description = "Millilitres",
                            Name = "ML"
                        },
                        new
                        {
                            UnitID = 9,
                            BusinessId = 0,
                            Description = "Dozen",
                            Name = "DOZ"
                        },
                        new
                        {
                            UnitID = 10,
                            BusinessId = 0,
                            Description = "Pair",
                            Name = "PAIR"
                        },
                        new
                        {
                            UnitID = 11,
                            BusinessId = 0,
                            Description = "Set",
                            Name = "SET"
                        },
                        new
                        {
                            UnitID = 12,
                            BusinessId = 0,
                            Description = "Packet",
                            Name = "PKT"
                        },
                        new
                        {
                            UnitID = 13,
                            BusinessId = 0,
                            Description = "Tin",
                            Name = "TIN"
                        },
                        new
                        {
                            UnitID = 14,
                            BusinessId = 0,
                            Description = "Bag",
                            Name = "BAG"
                        },
                        new
                        {
                            UnitID = 15,
                            BusinessId = 0,
                            Description = "Bottle",
                            Name = "BTL"
                        },
                        new
                        {
                            UnitID = 16,
                            BusinessId = 0,
                            Description = "Jar",
                            Name = "JAR"
                        },
                        new
                        {
                            UnitID = 17,
                            BusinessId = 0,
                            Description = "Can",
                            Name = "CAN"
                        },
                        new
                        {
                            UnitID = 18,
                            BusinessId = 0,
                            Description = "Tube",
                            Name = "TUBE"
                        },
                        new
                        {
                            UnitID = 19,
                            BusinessId = 0,
                            Description = "Roll",
                            Name = "ROLL"
                        },
                        new
                        {
                            UnitID = 20,
                            BusinessId = 0,
                            Description = "Sheet",
                            Name = "SHEET"
                        },
                        new
                        {
                            UnitID = 21,
                            BusinessId = 0,
                            Description = "Square Feet",
                            Name = "SQFT"
                        },
                        new
                        {
                            UnitID = 22,
                            BusinessId = 0,
                            Description = "Square Meter",
                            Name = "SQM"
                        },
                        new
                        {
                            UnitID = 23,
                            BusinessId = 0,
                            Description = "Cubic Feet",
                            Name = "CFT"
                        },
                        new
                        {
                            UnitID = 24,
                            BusinessId = 0,
                            Description = "Cubic Meter",
                            Name = "CUM"
                        });
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Designation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.Vendor", b =>
                {
                    b.Property<int>("VendorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GSTIN")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("GstTreatment")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("IFSC")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("VendorID");

                    b.HasIndex("BusinessId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.Customer", b =>
                {
                    b.HasOne("BusinessSuite.DAL.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.Invoice", b =>
                {
                    b.HasOne("BusinessSuite.DAL.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessSuite.DAL.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.InvoiceItem", b =>
                {
                    b.HasOne("BusinessSuite.DAL.Entities.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessSuite.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.Product", b =>
                {
                    b.HasOne("BusinessSuite.DAL.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("BusinessSuite.DAL.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessSuite.DAL.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("BusinessSuite.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessSuite.DAL.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.StockTransaction", b =>
                {
                    b.HasOne("BusinessSuite.DAL.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessSuite.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.Vendor", b =>
                {
                    b.HasOne("BusinessSuite.DAL.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BusinessSuite.DAL.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
